# =============================================================================
# Origin verification: CloudFront -> ALB shared header
# =============================================================================
# THE PROBLEM: an internet-facing ALB is reachable directly. Everything
# CloudFront enforces -- the WAF Web ACL, TLS policy, the response headers, the
# method restrictions -- is bypassed by anyone who resolves the ALB's own DNS
# name and connects to it. The Ingress cannot be made internal, because
# CloudFront reaches origins over the public internet.
#
# THE CONTROL: CloudFront sends a high-entropy header on every origin request.
# The REGIONAL Web ACL attached to the ALB (see waf-regional.tf) blocks any
# request whose header does not exactly match. Direct-to-ALB traffic does not
# have the value and is dropped at the ALB.
#
# It is defence in depth, not authentication -- it is a shared secret in a
# header, so it is only as strong as the confidentiality of that header. That
# is why the CloudFront-to-ALB hop is HTTPS (origin_protocol_policy =
# https-only) rather than plaintext.
#
# --- SECRET HANDLING, STATED PLAINLY -----------------------------------------
# DECISION: random_password, generated by Terraform.
#
# THE RAW VALUE WILL EXIST IN TERRAFORM STATE, IN PLAINTEXT. `sensitive = true`
# only redacts CLI output; it does nothing to the state file. Anyone who can
# read the state object can read this value.
#
# That is accepted here, and the mitigation is that the state file is treated
# as a secret store in its own right:
#   - the state bucket is encrypted with a dedicated CMK (bootstrap/),
#   - public access is blocked and TLS is enforced by bucket policy,
#   - the bucket policy denies every principal outside an explicit allow-list,
#   - reads are logged to a separate access-log bucket.
#
# THE ALTERNATIVE, if state exposure is unacceptable: create the secret with
# `generate_secret_string` on an aws_secretsmanager_secret, never read it back
# into Terraform, and have the WAF rule reference it indirectly (a small Lambda
# or an out-of-band `aws wafv2 update-web-acl`). That removes the value from
# state entirely, at the cost of a component that Terraform does not converge
# and that can silently drift out of sync with CloudFront's custom header --
# a failure mode that presents as a total outage, since every request would be
# blocked. random_password is chosen because a self-contained, converged
# configuration is worth more here than removing a value from a store that is
# already hardened.
#
# NOT DONE ANYWHERE: this value never appears in a distribution comment, a tag,
# a resource name, or a non-sensitive output. Those are the places that leak
# into CI logs.
# =============================================================================

resource "random_password" "origin_verify" {
  length = 64
  # Alphanumeric only. Header values must survive HTTP header encoding intact,
  # and WAFv2 byte-match statements compare raw bytes -- punctuation buys no
  # entropy worth the encoding risk. 64 alphanumeric chars is ~380 bits.
  special = false
}

# The Secrets Manager copy exists for rotation tracking and for humans doing
# incident response, NOT because anything reads it at runtime. The CloudFront
# custom header and the WAF byte-match rule both take the value directly from
# the random_password resource.
resource "aws_secretsmanager_secret" "origin_verify" {
  name        = var.origin_secret_name
  description = "Value of the ${local.origin_verify_header} header CloudFront sends to the ALB. Reference copy for rotation tracking; the live values are in the CloudFront distribution and the regional WAF rule."

  kms_key_id              = var.secret_kms_key_arn
  recovery_window_in_days = 7

  tags = merge(var.tags, { Name = var.origin_secret_name })
}

resource "aws_secretsmanager_secret_version" "origin_verify" {
  secret_id     = aws_secretsmanager_secret.origin_verify.id
  secret_string = random_password.origin_verify.result
}

locals {
  # A non-standard header name. x-origin-verify is conventional; the point is
  # that it is not a header any client or proxy sets on its own.
  origin_verify_header = "x-echo-pong-origin-verify"
}
