# =============================================================================
# Explicit cache / origin-request / response-headers policies
# =============================================================================
# These are written out rather than referencing AWS managed policies
# (Managed-CachingDisabled, Managed-AllViewerExceptHostHeader, ...) on purpose.
# The managed policies are AWS-owned objects whose definitions AWS can change,
# and reading `data.aws_cloudfront_cache_policy.managed_caching_disabled` in a
# review tells you nothing about what the cache key actually is. Explicit
# policies make the behaviour self-documenting and stable.
# =============================================================================

# -----------------------------------------------------------------------------
# Cache policy: no caching, anywhere
# -----------------------------------------------------------------------------
# /ping and /pong are authenticated endpoints whose response depends on a
# request header. Caching them would mean one client's authorised response
# could be served to another client -- so caching is disabled, not merely
# short-TTL'd.
#
# Note: CloudFront ALSO disables caching implicitly whenever Authorization is
# in the cache key or forwarded via certain managed policies. We do not rely on
# that side effect; TTLs are explicitly zero below.
resource "aws_cloudfront_cache_policy" "disabled" {
  provider = aws.useast1

  name        = "${var.name_prefix}-caching-disabled"
  comment     = "No caching. Every response is generated by the origin."
  default_ttl = 0
  min_ttl     = 0
  max_ttl     = 0

  parameters_in_cache_key_and_forwarded_to_origin {
    enable_accept_encoding_gzip   = true
    enable_accept_encoding_brotli = true

    cookies_config {
      cookie_behavior = "none"
    }

    headers_config {
      header_behavior = "none"
    }

    query_strings_config {
      query_string_behavior = "none"
    }
  }
}

# A short-TTL policy for the / docs page, wired but not used by default
# (default_root_object_cache_seconds = 0). It exists so enabling caching on the
# static page later is a variable change, not a new resource in a hurry.
resource "aws_cloudfront_cache_policy" "docs_page" {
  provider = aws.useast1

  name        = "${var.name_prefix}-docs-page"
  comment     = "Short-lived caching for the static / docs page."
  default_ttl = max(var.default_root_object_cache_seconds, 1)
  min_ttl     = 0
  max_ttl     = max(var.default_root_object_cache_seconds, 1)

  parameters_in_cache_key_and_forwarded_to_origin {
    enable_accept_encoding_gzip   = true
    enable_accept_encoding_brotli = true

    cookies_config {
      cookie_behavior = "none"
    }

    headers_config {
      header_behavior = "none"
    }

    query_strings_config {
      query_string_behavior = "none"
    }
  }
}

# -----------------------------------------------------------------------------
# Origin request policy: forward Authorization
# -----------------------------------------------------------------------------
# THE critical policy in this module. echo-pong compares the Authorization
# header against its loaded secret; if CloudFront does not forward it, every
# /ping and /pong request 401s and the failure looks like an app bug.
#
# Authorization is in the ORIGIN REQUEST policy, not the CACHE KEY policy. If
# it were in the cache key, CloudFront would cache per-credential responses --
# which is both a caching cost and, on a cache-key collision or a
# misconfiguration, a cross-tenant leak. Forwarding without keying is correct
# precisely because caching is disabled.
resource "aws_cloudfront_origin_request_policy" "authenticated" {
  provider = aws.useast1

  name    = "${var.name_prefix}-authenticated"
  comment = "Forwards Authorization and the standard client context to the origin."

  cookies_config {
    cookie_behavior = "none"
  }

  headers_config {
    header_behavior = "whitelist"

    headers {
      items = [
        "Authorization",
        "Accept",
        "Accept-Encoding",
        "User-Agent",
        "CloudFront-Viewer-Address",
        "CloudFront-Viewer-Country",
        # NOT forwarded: Host. The origin is addressed by origin_fqdn and the
        # ALB routes on it; forwarding the viewer Host would break the origin's
        # TLS SNI match.
      ]
    }
  }

  query_strings_config {
    query_string_behavior = "all"
  }
}

# The public endpoints do not need Authorization forwarded at all. A separate,
# narrower policy means a bug in the authenticated policy cannot widen what
# /health and / receive.
resource "aws_cloudfront_origin_request_policy" "public" {
  provider = aws.useast1

  name    = "${var.name_prefix}-public"
  comment = "Public endpoints. Authorization is deliberately NOT forwarded."

  cookies_config {
    cookie_behavior = "none"
  }

  headers_config {
    header_behavior = "whitelist"

    headers {
      items = [
        "Accept",
        "Accept-Encoding",
        "User-Agent",
        "CloudFront-Viewer-Country",
      ]
    }
  }

  query_strings_config {
    query_string_behavior = "none"
  }
}

# -----------------------------------------------------------------------------
# Response headers policy: security headers
# -----------------------------------------------------------------------------
resource "aws_cloudfront_response_headers_policy" "security" {
  provider = aws.useast1

  name    = "${var.name_prefix}-security-headers"
  comment = "HSTS, nosniff, referrer policy, frame denial, and a CSP for the docs page."

  security_headers_config {
    strict_transport_security {
      # 2 years, subdomains included. preload is left OFF: submitting to the
      # HSTS preload list is effectively irreversible on browser timescales and
      # would commit every current and future subdomain of this domain to
      # HTTPS-only, which is not this stack's decision to make unilaterally.
      access_control_max_age_sec = 63072000
      include_subdomains         = true
      preload                    = false
      override                   = true
    }

    content_type_options {
      override = true
    }

    referrer_policy {
      referrer_policy = "strict-origin-when-cross-origin"
      override        = true
    }

    frame_options {
      frame_option = "DENY"
      override     = true
    }

    xss_protection {
      # X-XSS-Protection is deprecated and its legacy filter has itself been a
      # source of vulnerabilities; the modern answer is the CSP below.
      # mode_block = false with protection = false emits "0", which explicitly
      # disables the legacy filter rather than leaving it to browser defaults.
      protection = false
      mode_block = false
      override   = true
    }

    content_security_policy {
      # The only HTML this origin serves is the self-contained docs page at /.
      # It has no external assets, so the policy can be maximally strict.
      content_security_policy = "default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'; frame-ancestors 'none'"
      override                = true
    }
  }

  custom_headers_config {
    items {
      header   = "Permissions-Policy"
      value    = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
      override = true
    }

    items {
      header   = "Cache-Control"
      value    = "no-store"
      override = false
    }
  }

  # No server-timing headers: they expose origin latency characteristics to
  # every client for no operational benefit here.
}
